### ISSUE TITLE
Q: DW compatibility? Plugin still maintained?

### ISSUE THREAD

**Issue by fthommen** [cosmocode/pagenav#15]
Hello,
this _extremely_ handy plugin is shown with a "possible compatibility problem" warning on https://www.dokuwiki.org/plugin:pagenav.  I am currently using it on two sites but I wonder, if the plugin is still maintained and if it is planned to keep it compatible with future DW versions.
Thanks

**Comment by splitbrain** [comment]
Even though the plugin worked fine as is, I gave a little polish.

**Comment by fthommen** [comment]
Thx, very appreciated.  The optical polish was worth it :-)
